


//class setup will be autogenerated upon successful verification
//Base file for jsTempFiles to run games

exports.run = (canvas, alert) => {
    try {

        //controller to determine time since program execution, as well as delay/wait/sleep (within thread)
        class time {
            static get time() {
                return Date.now()-time._time;
            }

            static get start(){
                return time._time;
            }

            static construct() {
                time._time = Date.now();

                time.wait = function (ms) {
                    let o = Date.now();
                    while (Date.now() < (o + ms)) {}
                }
            }


            //verification will throw error if any attempt to access _time is found
        };

        time.construct();

        //increase time every ms, so time = num of ms since execution

        //BEGIN USER CODE
        let x = 0, y = 0;
        while (true) {
        x = Math.abs(Math.sin(time.time/1000) * 100);
        y = Math.abs(Math.cos(time.time/1000) * 100);
        
        time.wait(10);
        
        canvas("fillStyle = '#FFFFFF'");
        canvas("fillRect(0,0,1920,1080)");
        canvas("fillStyle = '#000000'");
        canvas(`fillText('${time.time}', ${x} , ${y})`);
        }
        //END USER CODE
    } catch (e) {
        alert(e);
    }
}